// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eevjpbddnzowxhajavdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVldmpwYmRkbnpvd3hoYWphdmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODk0NTMsImV4cCI6MjA3MTI2NTQ1M30.k52EB-AY2RV0GQmSQzaL4urhh8HN7rzqqqXrAMgHrj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});